[phases.setup]
nixPkgs = ["python311", "ffmpeg-full"]

[phases.install]
cmds = [
    "python3.11 -m venv --clear /opt/venv",
    ". /opt/venv/bin/activate && pip install --no-cache-dir --upgrade pip",
    ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && python youtube_bot.py"
# Force rebuild timestamp: 2025-10-25T15:15:00Z
