# Railway Config for Local Bot API Service
# Faqat telegram-local-api service uchun

# Builder type
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.localapi"

# Deploy settings
[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
